version: '3.4'

services:
  django-server:
    image: django-server
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - app/.env
    volumes:
      - static_volume:/app/static
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_DATABASE: aou
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mariadb_data:
