version: '3.4'

services:
  django:
    image: django-server
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 aou.wsgi:application
    env_file:
      - app/.env
    volumes:
      - static_volume:/app/static
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_DATABASE: aou
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - django
    volumes:
      - static_volume:/app/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mariadb_data:
  static_volume:
