# Generated by Django 4.0.5 on 2022-06-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': '연주회',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '악기',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('univ', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '가입자',
            },
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('agreement', models.TextField()),
                ('concert', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orchestra.concert')),
                ('instruments', models.ManyToManyField(to='orchestra.instrument')),
            ],
            options={
                'verbose_name_plural': '지원서 양식',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=True)),
                ('is_del', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motive', models.TextField()),
                ('career', models.TextField()),
                ('etc', models.TextField(blank=True)),
                ('is_activate', models.BooleanField()),
                ('is_pass', models.BooleanField()),
                ('is_leave', models.BooleanField()),
                ('concert', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orchestra.concert')),
                ('instrument', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orchestra.instrument')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='orchestra.user')),
            ],
            options={
                'verbose_name_plural': '지원자',
            },
        ),
    ]
